version: '3.7'

services:
  db:
    image: postgres:15.1-alpine
    container_name: ad_service_db
    environment:
      POSTGRES_DB: "ad_service_db"
      POSTGRES_USER: "urbanus"
      POSTGRES_PASSWORD: "mds2ids#skibidiToi1e+?"
    ports:
      - "5433:5432"
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urbanus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# volumes:
#   db_data:
    # This named volume will store the PostgreSQL data
